/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 * @nolint
 * @oncall ws_labs
 */

/**
 * * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    'installation',
    'getting-started',
    'cli/CLI-commands',
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    'how-memlab-works',
    {
      type: 'category',
      label: 'API reference',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

module.exports = sidebars;
